<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Cuidador extends Model
{
    protected $fillable = [
        'nombre',
        'edad',
    ];

    public function cuidadoranimals()
    {
        return $this->hasMany('App\Models\CuidadorAnimal', 'cuidador_id');
    }

    public function especies()
    {
        return $this->hasMany('App\Models\Especie', 'cuidador_id');
    }
}
